
export const UPDATE_FILE = 'UPDATE_FILE';

export const ADD_FILES = 'ADD_FILES';

export const ADD_LIBRARY_FILES = 'ADD_LIB_FILES';

export const REMOVE_FILE = 'REMOVE_FILE';

export const REMOVE_ALL_FILES = 'REMOVE_ALL_FILES';

export const CONVERT_PROGRESS = 'CONVERT_PROGRESS';

export const CONVERT_COMPLETE = 'CONVERT_COMPLETE';